name: synapsis_challenge
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  floor: ^1.4.1
  floor_annotation: ^1.4.1
  flutter:
    sdk: flutter
  get: 4.6.5
  path: ^1.8.2
  sqflite: ^2.2.4+1

dev_dependencies:
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
