name: synapsis_challenge
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  battery_plus: ^3.0.2
  build_runner: ^2.3.3
  camera: ^0.10.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_table_2: ^2.3.12
  device_info_plus: ^8.0.0
  fl_chart: ^0.60.0
  flex_color_scheme: ^6.1.2
  floor: ^1.4.1
  floor_annotation: ^1.4.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_map: ^3.1.0
  form_builder_validators: ^8.4.0
  geolocator: ^9.0.2
  get: 4.6.5
  google_fonts: ^4.0.3
  image: ^4.0.13
  intl: ^0.17.0
  latlong2: ^0.8.1
  liquid_progress_indicator: ^0.4.0
  loading_overlay: ^0.3.0
  nfc_manager: ^3.2.0
  oscilloscope: ^0.2.0+1
  package_info_plus: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.12
  qr_flutter: ^4.0.0
  sensors_plus: ^2.0.1
  shared_preferences: ^2.0.17
  sqflite: ^2.2.4+1
  stamp_image: ^0.0.2

dev_dependencies:
  floor_generator: ^1.4.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
